# Config file for compose, a tool that allows for easily managing multiple containers.
# https://docs.docker.com/compose/

services:
    database:
        # not :nightly because doing that once caused failures when graph linking
        # and also caused errors with query parameters (twice)
        build: ./Database
        ports:
            - 8000:8000
        restart: unless-stopped
        volumes:
            - ./data/surreal:/database
        command:
            - start
            - -u=root
            - -p=root
            - surrealkv://database

    economy:
        build: ./Economy
        ports:
            - 2009:2009
        restart: unless-stopped
        volumes:
            - ./data/economy:/data/economy

    site:
        build: .
        ports:
            - 4443:4443
        restart: unless-stopped
        depends_on:
            - database # will keep retrying until database is ready
            - economy
